NETWORK_PREFIX = "192.168.151"

Vagrant.configure("2") do |config|
    config.vm.define "podman" do |podman|
        podman.vm.box = "generic/rhel9"
        podman.vm.hostname = "podman"
        podman.vm.network :private_network, ip: "#{NETWORK_PREFIX}.10"
    end
end
